# Generated by Django 5.2.1 on 2025-06-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idIventario', models.AutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.CharField(max_length=4)),
                ('fechaInventario', models.DateField()),
                ('horaInventario', models.TimeField(auto_now_add=True)),
                ('estadoInventario', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('idDetalleInventario', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateField()),
                ('horaIngreso', models.TimeField()),
                ('fechaCaducidad', models.DateField()),
                ('cantidadProducto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idProducto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='Gestion_productos.producto')),
                ('idInventario', models.ForeignKey(db_column='idInventario', on_delete=django.db.models.deletion.CASCADE, to='Gestion_Inventario.inventario')),
            ],
        ),
    ]
