# Generated by Django 5.2.1 on 2025-06-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleinventario',
            table='DetalleInventario',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='Inventario',
        ),
    ]
