# Generated by Django 5.2.1 on 2025-06-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0002_alter_detalleinventario_table_alter_inventario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='estadoInventario',
        ),
        migrations.AddField(
            model_name='inventario',
            name='sePuedeEditar',
            field=models.BooleanField(default=True),
        ),
    ]
