# Generated by Django 5.2.1 on 2025-06-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0002_alter_inventario_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='idIventario',
            new_name='idInventario',
        ),
    ]
