# Generated by Django 5.2.1 on 2025-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inventario', '0003_rename_idiventario_inventario_idinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinventario',
            name='cantidadProducto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
