# Generated by Django 5.2.1 on 2025-10-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='receta',
            name='idReceta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
