# Generated by Django 5.2.1 on 2025-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Recetas', '0002_remove_categoria_id_remove_receta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='estaHabilitadoReceta',
            field=models.BooleanField(default=True),
        ),
    ]
