# Generated by Django 5.2.1 on 2026-01-27 08:03

import django.db.models.deletion
from django.db import migrations, models


def migrar_categorias_y_recetas(apps, schema_editor):
    """
    Migra las categorías existentes de Gestion_Recetas a CategoriaProductoMenu
    y actualiza las referencias en las recetas
    """
    Categoria = apps.get_model('Gestion_Recetas', 'Categoria')
    CategoriaProductoMenu = apps.get_model('Gestion_Menu', 'CategoriaProductoMenu')
    Receta = apps.get_model('Gestion_Recetas', 'Receta')
    
    # Crear un mapa de categorías antiguas a nuevas
    mapeo_categorias = {}
    
    for categoria_vieja in Categoria.objects.all():
        # Buscar si ya existe una categoría similar en CategoriaProductoMenu
        categoria_nueva = CategoriaProductoMenu.objects.filter(
            nombreCategoriaProductoMenu=categoria_vieja.nombreCategoria
        ).first()
        
        # Si no existe, crearla
        if not categoria_nueva:
            categoria_nueva = CategoriaProductoMenu.objects.create(
                nombreCategoriaProductoMenu=categoria_vieja.nombreCategoria
            )
        
        mapeo_categorias[categoria_vieja.idCategoria] = categoria_nueva.idCategoriaProductoMenu
    
    # Actualizar las recetas con las nuevas categorías
    for receta in Receta.objects.all():
        if receta.Categoria_id in mapeo_categorias:
            receta.Categoria_id = mapeo_categorias[receta.Categoria_id]
            receta.save()


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión (opcional, puede dejar pasar si no se necesita)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Menu', '0001_initial'),
        ('Gestion_Recetas', '0003_receta_estahabilitadoreceta'),
    ]

    operations = [
        # Primero, permitir que el campo sea null temporalmente
        migrations.AlterField(
            model_name='receta',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Recetas.categoria'),
        ),
        # Ejecutar la migración de datos
        migrations.RunPython(migrar_categorias_y_recetas, revertir_migracion),
        # Cambiar el ForeignKey a la nueva tabla
        migrations.AlterField(
            model_name='receta',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Menu.categoriaproductomenu'),
        ),
        # Eliminar el modelo antiguo
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
