# Generated by Django 5.2.1 on 2025-10-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Proveedores', '0002_remove_proveedor_logourl_proveedor_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('idPedidoProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedidoProveedor', models.DateTimeField(auto_now_add=True)),
                ('sePuedeEditarPP', models.BooleanField(default=True)),
                ('totalPP', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finalizado', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Gestion_Proveedores.proveedor')),
            ],
            options={
                'db_table': 'PedidoProveedor',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('idDetallePedidoProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadPP', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subTotalPP', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Proveedores.productoproveedor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Gestion_compra_productos.pedidoproveedor')),
            ],
            options={
                'db_table': 'DetallePedidoProveedor',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
