# Generated by Django 5.2.1 on 2025-10-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_compra_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='contratoEmpleado',
            field=models.FileField(blank=True, null=True, upload_to='PedidosPP/'),
        ),
    ]
