# Generated by Django 5.2.1 on 2025-10-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=30)),
                ('apellidoCliente', models.CharField(max_length=30)),
                ('duiCliente', models.CharField(max_length=10)),
                ('telefonoCliente', models.CharField(max_length=9)),
                ('emailCliente', models.EmailField(max_length=50)),
                ('nacimientoCliente', models.DateField()),
                ('estaHabilitadoCliente', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Clientes.cliente')),
            ],
            options={
                'db_table': 'DireccionCliente',
            },
        ),
    ]
