# Generated by Django 5.2.1 on 2025-11-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacimientoCliente',
            field=models.DateField(null=True),
        ),
    ]
