# Generated by Django 5.2.1 on 2025-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('unidadMedida', models.CharField(max_length=20)),
                ('marcaProducto', models.CharField(max_length=20)),
                ('descripcionProducto', models.TextField()),
            ],
        ),
    ]
