# Generated by Django 5.2.1 on 2025-06-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
