# Generated by Django 5.2.1 on 2025-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estaHabilitadoProveedor',
            field=models.BooleanField(default=True),
        ),
    ]
