# Generated by Django 5.2.1 on 2025-06-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_productos', '0002_producto_estahabilitadoproveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estaHabilitadoProveedor',
            new_name='estaHabilitadoProducto',
        ),
    ]
