# Generated by Django 5.2.1 on 2025-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('idMaquinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMaquinaria', models.CharField(max_length=120)),
                ('fechaCompraMaquinaria', models.DateField()),
                ('marcaMaquinaria', models.CharField(max_length=80)),
                ('estaHabilitadaMaquinaria', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Maquinaria',
                'ordering': ['idMaquinaria'],
            },
        ),
    ]
