# Generated by Django 5.2.1 on 2025-06-14 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEncargado', models.CharField(max_length=30)),
                ('apellidoEncargado', models.CharField(max_length=30)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('tieneIva', models.BooleanField(default=False)),
                ('telProveedor', models.CharField(max_length=9)),
                ('duiEncargado', models.CharField(max_length=10)),
                ('emailProveedor', models.EmailField(max_length=50)),
                ('ubicacionProveedor', models.TextField()),
                ('logoURL', models.TextField()),
                ('estaHabilitadoProveedor', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='HorarioProveedor',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horaApertura', models.TimeField()),
                ('horaCierre', models.TimeField()),
                ('diaSemana', models.CharField(max_length=15)),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Proveedores.proveedor')),
            ],
            options={
                'db_table': 'HorarioProveedor',
            },
        ),
    ]
