# Generated by Django 5.2.1 on 2025-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estaHabilitadoProveedor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedor',
        ),
    ]
