# Generated by Django 5.2.1 on 2025-06-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='logoURL',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
