# Generated by Django 5.2.1 on 2025-06-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProductoProveedor', models.CharField()),
                ('precioProductoProveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Proveedores.proveedor')),
            ],
            options={
                'db_table': 'ProductoProveedor',
            },
        ),
    ]
