# Generated by Django 5.2.1 on 2025-10-27 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMantenimiento', models.DateField()),
                ('esCorrectivo', models.BooleanField(default=False)),
                ('nombreTecnico', models.CharField(max_length=120)),
                ('fotoAntesURL', models.ImageField(blank=True, null=True, upload_to='mantenimientos/antes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('fotoDespuesURL', models.ImageField(blank=True, null=True, upload_to='mantenimientos/despues/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('fotoFacturaURL', models.ImageField(blank=True, null=True, upload_to='mantenimientos/facturas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='Gestion_Maquinaria.maquinaria')),
            ],
            options={
                'db_table': 'Gestion_Mantenimiento_mantenimiento',
                'ordering': ['-fechaMantenimiento', '-idMantenimiento'],
            },
        ),
    ]
