# Generated by Django 5.2.1 on 2025-11-14 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=120)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('tipo_reserva', models.CharField(choices=[('COMUN', 'Común'), ('EVENTO', 'Evento')], default='COMUN', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_mesa_creadas', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas_mesa.mesa')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
