# Generated by Django 5.2.1 on 2025-11-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_mesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('RESERVADA', 'Reservada'), ('OCUPADA', 'Ocupada')], default='LIBRE', max_length=10),
        ),
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('CIRCULO', 'Círculo'), ('RECT', 'Rectángulo'), ('ROMBO', 'Rombo')], default='RECT', max_length=10),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_y',
            field=models.IntegerField(default=50),
        ),
    ]
