# Generated by Django 5.2.1 on 2025-11-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_mesa', '0002_mesa_estado_mesa_forma_mesa_pos_x_mesa_pos_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='pos_y',
        ),
        migrations.AddField(
            model_name='mesa',
            name='columna',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesa',
            name='fila',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
