# Generated by Django 5.2.1 on 2025-11-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_mesa', '0003_remove_mesa_pos_x_remove_mesa_pos_y_mesa_columna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('CIRCULO', 'Circulo'), ('RECT', 'Rectangulo'), ('ROMBO', 'Rombo')], default='RECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservamesa',
            name='tipo_reserva',
            field=models.CharField(choices=[('COMUN', 'Comun'), ('EVENTO', 'Evento')], default='COMUN', max_length=10),
        ),
    ]
