# Generated by Django 5.2.1 on 2025-11-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_mesa', '0004_alter_mesa_forma_alter_reservamesa_tipo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('CIRCULO', 'Círculo'), ('RECT', 'Rectángulo'), ('ROMBO', 'Rombo')], default='RECT', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservamesa',
            name='tipo_reserva',
            field=models.CharField(choices=[('COMUN', 'Común'), ('EVENTO', 'Evento')], default='COMUN', max_length=10),
        ),
    ]
