# Generated by Django 5.2.1 on 2025-10-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Clientes', '0001_initial'),
        ('Gestion_Menu', '0001_initial'),
        ('empleado', '0007_alter_asistencia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedidoCliente',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EstadoPedidoCliente',
            },
        ),
        migrations.CreateModel(
            name='TipoPedidoCliente',
            fields=[
                ('idTipoPedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoPedido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TipoPedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('idPedidoCliente', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedidoCliente', models.DateField()),
                ('horaPedidoCliente', models.DateTimeField()),
                ('numCorrelativo', models.CharField(max_length=20)),
                ('totalPedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Clientes.cliente')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='ManipulacionPedido',
            fields=[
                ('idManipulacion', models.AutoField(primary_key=True, serialize=False)),
                ('esNuevoRegistro', models.BooleanField(default=False)),
                ('horaManipulacion', models.DateTimeField()),
                ('fechaManipulacion', models.DateField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('IdPedidoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Pedidos_Clientes.pedidocliente')),
            ],
            options={
                'db_table': 'ManipulacionPedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetallePedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadPedido', models.IntegerField()),
                ('subtotalPedido', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Menu.productomenu')),
                ('idPedidodCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Pedidos_Clientes.pedidocliente')),
            ],
            options={
                'db_table': 'DetallePedido',
            },
        ),
    ]
