# Generated by Django 5.2.1 on 2025-11-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Clientes', '0001_initial'),
        ('Gestion_Pedidos_Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='idPedidodCliente',
            new_name='idPedidoCliente',
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='idMesa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidocliente',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Clientes.cliente'),
        ),
    ]
