# Generated by Django 5.2.1 on 2025-11-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos_Clientes', '0002_rename_idpedidodcliente_detallepedido_idpedidocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='estadoPedido',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Gestion_Pedidos_Clientes.estadopedidocliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='horaRecoger',
            field=models.DateTimeField(null=True),
        ),
    ]
