# Generated by Django 5.2.1 on 2025-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos_Clientes', '0003_pedidocliente_comentario_pedidocliente_estadopedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocliente',
            name='idMesa',
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='direccionPedido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
