# Generated by Django 5.2.1 on 2025-11-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos_Clientes', '0004_remove_pedidocliente_idmesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='tipoPedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Pedidos_Clientes.tipopedidocliente'),
            preserve_default=False,
        ),
    ]
