# Generated by Django 5.2.1 on 2025-11-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos_Clientes', '0005_pedidocliente_tipopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='mesasPedido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
