# Generated by Django 5.2.1 on 2025-11-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos_Clientes', '0006_pedidocliente_mesaspedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='horaPedidoCliente',
            field=models.TimeField(),
        ),
    ]
