# Generated by Django 5.2.1 on 2025-11-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos_Clientes', '0007_alter_pedidocliente_horapedidocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='encomendista',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
