# Generated by Django 5.2.1 on 2025-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_crear_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estaHabilitadoUsuario',
            field=models.BooleanField(default=True),
        ),
    ]
