# Generated by Django 5.2.1 on 2025-10-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductoMenu',
            fields=[
                ('idCategoriaProductoMenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoriaProductoMenu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CategoriaProductoMenu',
            },
        ),
        migrations.CreateModel(
            name='ProductoMenu',
            fields=[
                ('idProductoMenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProductoMenu', models.CharField(max_length=50)),
                ('tamanioProductoMenu', models.CharField(max_length=20)),
                ('descripcionProductoMenu', models.TextField()),
                ('estaHabilitadoProductoMenu', models.BooleanField(default=True)),
                ('precioProductoMenu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idCategoriaProductoMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Menu.categoriaproductomenu')),
            ],
            options={
                'db_table': 'ProductoMenu',
            },
        ),
    ]
