# Generated by Django 5.2.1 on 2025-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('nombresEmpleado', models.CharField(max_length=30)),
                ('apellidosEmpleado', models.CharField(max_length=30)),
                ('duiEmpleado', models.CharField(max_length=10)),
                ('fechaNacimientoEmpleado', models.DateField()),
                ('telEmpleado', models.CharField(max_length=8)),
                ('telEmergenciaEmpleado', models.CharField(max_length=8)),
                ('salarioEmpleado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('experienciaLaboral', models.TextField()),
                ('fechaContratacion', models.DateField()),
                ('contratoEmpleado', models.FileField(upload_to='contratos/')),
            ],
        ),
    ]
