# Generated by Django 5.2.1 on 2025-06-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='experienciaLaboral',
            new_name='experienciaLaboralEmpleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fechaContratacion',
            new_name='fechaContratacionEmpleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='estaHabilitadoEmpleado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contratoEmpleado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idEmpleado',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salarioEmpleado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
