# Generated by Django 5.2.1 on 2025-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_rename_experiencialaboral_empleado_experiencialaboralempleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contratoEmpleado',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
