# Generated by Django 5.2.1 on 2025-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_empleado_contratoempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='idEmpleado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
