# Generated by Django 5.2.1 on 2025-06-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_idempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccionEmpleado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
