# Generated by Django 5.2.1 on 2025-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_asistencia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asistencia',
            table='Asistencia',
        ),
    ]
